knit_output_format: github_document
experiment:
  data_path: /input
  input_structure: '{data_path}/2022_06_05_CellPainting_normalized_negcon_time_feature_select.{extension}'
  extension: csv
  plates: ~
  external_metadata: ~
  add_dummy_metadata_column: yes
  split_by_column: ~
  significance_threshold: 0.05
  parallel_workers: 8
  aggregate_by: ~
  filter_by: ~
  reference_set:
    Metadata_control_type: negcon
  random_seed: 42
  background_type: ref
  shuffle: no
  shuffle_bad_groups_threshold: ~
  shuffle_group: ~
  shuffle_strata: ~
  shuffle_exclude: ~
  subsample_fraction: 1
  subsample_pert_strata: ~
  subsample_reference_strata: ~
  similarity_method: cosine
  sim_params:
    reference:
      Metadata_reference_or_other: reference
    all_same_cols_ref: Metadata_dummy
    all_same_cols_rep:
    - Metadata_Compound_concentration
    - Metadata_reference_or_other
    all_different_cols_rep: ~
    any_different_cols_rep: ~
    all_same_cols_rep_ref: ~
    any_different_cols_non_rep: ~
    all_same_cols_non_rep: ~
    all_different_cols_non_rep: ~
    all_same_cols_group: ~
    any_different_cols_group: ~
    annotation_cols:
    - Metadata_Compound_concentration
    - Metadata_Compound
    - Metadata_Concentration
    - Metadata_reference_or_other
